#ifndef GAM703_ENGINE_GRAPHIC_CONFIG_HPP
#define GAM703_ENGINE_GRAPHIC_CONFIG_HPP

#ifdef ENGINE_GRAPHIC_EXPORT
#define ENGINE_GRAPHIC_API __declspec(dllexport)
#else
#define ENGINE_GRAPHIC_API __declspec(dllimport)
#endif


#endif // GAM703_ENGINE_GRAPHIC_CONFIG_HPP
