#ifndef GAM703_ENGINE_COMPONENTS_CONFIG_HPP
#define GAM703_ENGINE_COMPONENTS_CONFIG_HPP

#ifdef ENGINE_COMPONENTS_EXPORT
#define ENGINE_COMPONENTS_API __declspec(dllexport)
#else
#define ENGINE_COMPONENTS_API __declspec(dllimport)
#endif

#endif // GAM703_ENGINE_COMPONENTS_CONFIG_HPP
