#ifndef GAM703_ENGINE_COMPONENTS_CONFIG_HPP
#define GAM703_ENGINE_COMPONENTS_CONFIG_HPP

#ifdef ENGINE_COMPONENTS_DLL
#ifdef ENGINE_COMPONENTS_EXPORT
#define ENGINE_COMPONENTS_API __declspec(dllexport)
#else
#define ENGINE_COMPONENTS_API __declspec(dllimport)
#endif //ENGINE_COMPONENTS_EXPORT
#else
#define ENGINE_COMPONENTS_API
#endif // ENGINE_COMPONENTS_DLL

#endif // GAM703_ENGINE_COMPONENTS_CONFIG_HPP
