#ifndef GAM703_ENGINE_CORE_INTERFACES_TRANSFORM_FWD_HPP
#define GAM703_ENGINE_CORE_INTERFACES_TRANSFORM_FWD_HPP

namespace gam703::engine::core_interface
{
	class Transform;
}

#endif // GAM703_ENGINE_CORE_INTERFACES_TRANSFORM_FWD_HPP
