#ifndef GAM703_ENGINE_UTILITY_CONFIG_HPP
#define GAM703_ENGINE_UTILITY_CONFIG_HPP

#ifdef ENGINE_UTILITY_EXPORT
#define ENGINE_UTILITY_API __declspec(dllexport)
#else
#define ENGINE_UTILITY_API __declspec(dllimport)
#endif

#endif // GAM703_ENGINE_UTILITY_CONFIG_HPP
